In [2]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv("play_tennis.csv")
df.drop(columns = ["day"], inplace = True)

In [7]:
df.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

# Problem 1

# Outlook = sunny, Temp = Hot, Humidity = High, Wind = weak
# play or no No play

# solution

# P(Yes | Suuny, Hot, weak)  = P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes) * P(Yes)

# P(No | Suuny, Hot, weak) = P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No) * P(No)

# Compare and decide using the maximum a posteriori rule

# problem 2

# outlook-Ovecast, Temp = Cold, Humidity = Low, wind = Weak

# play or No play?

# P(Yes | Overcast, cold, Low, Weak) = P(overcast | Yes) *P(Cold | Yes) * P(Low | Yes) * P(Weak | Yes) * P(Yes)
# # P(No | Overcast, cold, Low, Weak) = P(overcast | No) *P(Cold | No) * P(Low | No) * P(Weak | No) * P(No)

# Training
# look-up table
# testing

In [10]:
# P(Yes)
# P(No)
df["play"].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [12]:
py = 9 / 14
pn = 5 / 14
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [14]:
# outlook column
pd.crosstab(df["outlook"], df["play"])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [15]:
pon = 0 / 5
prn = 2 / 5
psn = 3 / 5

poy = 4 / 9
pry = 3 / 9
psy = 2 / 9

In [17]:
# temperature

pd.crosstab(df["temp"], df["play"])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [18]:
pCoolNo = 1 / 5
pHotNo = 2 / 5
pMildNo = 2 / 5

pCoolYes = 3 / 9
pHotYes = 2 / 9
pMildYes = 4 / 9

In [20]:
# humid
pd.crosstab(df["humidity"], df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [25]:
pHighNo = 4 / 5
pNormalNo = 1 / 5

pHighYes = 3 / 9
pNormalYes = 6 / 9

In [23]:
# wind
pd.crosstab(df["wind"], df["play"])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [34]:
pStrongNo = 3 / 5
pWeakNo = 2 / 5

pStrongYes = 3 / 9
pWeakYes = 6 / 9

In [35]:
# outlook sunny, temp = Hot, Humidity = high, wind = weak

pYes = py * psy * pHotYes * pHighYes * pWeakYes

In [36]:
pYes

0.007054673721340388

In [33]:
pNo = pn * psn * pHotNo * pHighNo * pWeakNo
print(pNo)

0.02742857142857143

# No Play